### ISSUE TITLE
Discrepancy calling harp.compile()

### ISSUE THREAD

**Issue by ebsen** [sintaxi/harp#391] opened 2014-12-10 03:53 UTC
I'm getting the following error calling `harp.compile();` from within a gulp task:

```
/Users/erik/Sites/holiday14/node_modules/harp/lib/index.js:245
            callback(null, setup.config)
            ^
TypeError: undefined is not a function
  at /Users/erik/Sites/holiday14/node_modules/harp/lib/index.js:245:13
  at /Users/erik/Sites/holiday14/node_modules/harp/node_modules/async/lib/async.js:185:33
  at ReadStream.cb (/Users/erik/Sites/holiday14/node_modules/harp/node_modules/fs-extra/node_modules/ncp/lib/ncp.js:217:38)
  at ReadStream.g (events.js:180:16)
  at ReadStream.emit (events.js:117:20)
  at _stream_readable.js:943:16
  at process._tickCallback (node.js:419:13)
```

If I provide a callback (even an empty one) as the final argument to `compile()`, I don't receive the error. However, from [the Lib section of the README](https://github.com/sintaxi/harp/blob/master/README.md#lib-usage) and [the `compile` function starting on line 145 of harp/lib/index.js](https://github.com/sintaxi/harp/blob/master/lib/index.js), only the `projectPath` argument seems required. 

Confusing matters further, the first _comment_ inside lib/index.js states "projectPath and outputPath are optional"—even though the code right below it seems to assign default values to `outputPath` and `callback` if not provided.

I guess from the code itself and from the README, it looks like only the `projectPath` argument is required. That makes perfect sense to me. It just doesn't jive with the behavior I'm seeing.

If I can clarify myself or help in any way, please let me know.

**Comment by richardo2016** [comment] 2015-05-01 14:46
As u say , if we don't provide the an argument to che param `callback` ,we will get the error—— u can avoid it if u don't put all ur files of our website into the directory `public`.

it's an omit of the author , I guess the author suppose the user of harp would build one entrance file (maybe named `myfile.js`) and build directory named `public` at the same directory of `myfile.js` , then u won't get the error as ur description :)

**Comment by ccprog** [comment] 2017-08-12 23:27
The defaults implementation is plain wrong. It assumes that, if there are only two parameters present, the second is always a callback, see [lib/index.js#L163](https://github.com/sintaxi/harp/blob/master/lib/index.js#L163):

1. `harp.compile("srcDir", "destDir", function(){})` is left as is.
2. `harp.compile("srcDir", "destDir")` is mapped to `harp.compile("srcDir", "www", "destDir")`.
3. `harp.compile("srcDir",  function(){})` is mapped to `harp.compile("srcDir", "www",  function(){})`.
2. `harp.compile("srcDir")` is mapped to `harp.compile("srcDir", "www", null)`.

**Comment by misterhtmlcss** [comment] 2018-10-21 15:31
We are closing this issue and will discuss with @ccprog to confirm the issue is still current and then consider it for inclusion. Thank you @ebsen for the issue and I'm very sorry it took so long to address here. We are getting back up to speed on things now.

**Closed by misterhtmlcss** 2018-10-21 15:31 UTC
Labels: bug
