### ISSUE TITLE
server & compile should have parity where possible

### ISSUE THREAD

**Issue by drewhamlett** [sintaxi/harp#149] opened 2013-11-07 15:15 UTC
From using other static site generators, I'm use to seeing articles/first.html get compiled to articles/first/index.html.  Why is this not the case?  Or am I missing an option.

**Comment by opichon** [comment] 2015-02-16 23:57
I can see the logic for not adding the .html extension to links during compilation, but this does mean that a harp site cannot realistically be used  in a non-harp server environment such as s3, unless all links are fixed by hand in the code -- or am I missing something?

For example, if my "about" page is defined in the root (or public) folder, and referenced in the source code as `a(href="/about")`, then the compiled link's `href` attribute will remain unchanged ("/about") and will not work when the site is published to S3. Converting `/public/about.jade` to `public/about/index.jade` works, but it means having 1 directory per page, which is cumbersome. And of course this solution does not work for blog posts, which by construction are stored under the same folder; so the links to the blog posts in the `blog/index` page are not working in S3, since they do not have a .html extension.

So pretty much the only solution is to add the ".html" extension to each link by hand in the source code. Whether or not this is an insurmountable inconvenience is for each one to decide, but it would be good to be aware of it at first, before writing a whole site and finding out that the links don't work. More importantly, does this cause some incompatibilities when the site is run in harp server?

**Comment by sintaxi** [comment] 2015-02-17 00:02
Harp handles these urls just fine. IMHO this is a bug in all OTHER web servers. The lack of sane defaults such as this in other web servers was motivation for creating harp in the first place.

**Comment by daku** [comment] 2016-01-22 22:07
The harp service handles it just fine, the problem is with 'harp compile'. Why not have 'harp compile' take an input for a root path? Then, prepend all absolute references with the root path.

**Comment by tay1orjones** [comment] 2016-06-02 19:37
There's a workaround I found with using the NODE_ENV variable and a base tag - see my comment on #530

**Closed** 2019-10-25 03:08 UTC
Labels: feature-request, implementation
