### ISSUE TITLE
Give option to skip minification

### ISSUE THREAD

**Issue by tagCincy** [sintaxi/harp#406] opened 2015-02-11 18:40 UTC
Updated from 0.14.0 to 0.15.1 and noticed that now all my Coffeescript is minified when I run my app locally.  Minification is a really good thing, however, it is a complete pain to deal with in a dev environment.  

It would be nice if we could tell Harp not to minify when launching the server locally.

**Comment by kennethormandy** [comment] 2015-02-25 03:37
Hey, thanks. Ideally, Harp would support source maps #74 so this wouldn’t be an issue, but we haven’t been able to get to that yet.

Otherwise, I think this is a duplicate of #169 where we were discussing if minification should be configurable. Thank you for opening an issue, and feel free to post any other comments there!

**Closed by kennethormandy** 2015-02-25 03:37 UTC
